In [2]:
import pandas as pd

In [46]:
df = pd.read_excel('/Users/a19028558/Desktop/Ralf_Hack/furniture_2020.xls')

In [47]:
df.columns = df.iloc[1]
df = df[2:]
df.head()

1,NaN,NaN,NaN,NaN,январь,февраль,март,апрель,май,июнь,июль,август,сентябрь,октябрь,ноябрь,декабрь
2,2020.0,К декабрю предыдущего года,Российская Федерация,"Пески природные, не включенные в другие гр...",100.31,102.15,104.69,111,111.17,108.86,106.07,104.17,104.19,107.15,105.86,105.07
3,2020.0,К декабрю предыдущего года,Российская Федерация,Гравий,99.88,101.58,101,100.29,100.62,101.76,101.98,103.47,102.83,103.39,103.29,103.23
4,2020.0,К декабрю предыдущего года,Российская Федерация,Щебень,99.12,98.21,98.7,98.55,98.83,98.27,98.46,98.38,98.07,97.7,97.85,97.54
5,2020.0,К декабрю предыдущего года,Российская Федерация,Камень природный дробленый,99.41,89.19,100.33,100.21,98.13,98.16,116.28,98.44,98.19,126.98,127.87,128.25
6,2020.0,К декабрю предыдущего года,Российская Федерация,Смеси песчано-гравийные,100.33,101.48,101.75,102.08,102.1,103.68,104.43,106.02,107.27,107.46,107.42,107.33

In [56]:
df_transponse = df.T.reset_index()

In [34]:
df_raif = pd.read_csv('/Users/a19028558/Desktop/Ralf_Hack/train.csv')
# df_raif['date'].value_counts()

In [36]:
dates_raif = set(df_raif['date'])

In [57]:
df_transponse.columns = df_transponse.iloc[3]
df_transponse = df_transponse[4:]

In [75]:
df_transponse.rename(columns={df_transponse.columns[0]:'date'}, inplace=True)

In [94]:

date_collector = {}
for i, date in enumerate(df_transponse['date']):
    i += 1
    key = f'0{i}' if i < 10 else str(i)
    date_collector[key] = date
    
date_collector

{'01': 'январь',
 '02': 'февраль',
 '03': 'март',
 '04': 'апрель',
 '05': 'май',
 '06': 'июнь',
 '07': 'июль',
 '08': 'август',
 '09': 'сентябрь',
 '10': 'октябрь',
 '11': 'ноябрь',
 '12': 'декабрь'}

In [96]:
mapping = {}
for date in list(dates_raif):
    if date.split('-')[1] in date_collector:
        mapping[date] = date_collector[date.split('-')[1]]
    else:
        print('f')

In [111]:
df_raif['month'] = df_raif['date'].apply(lambda x: mapping[x])

In [116]:
df_transponse.rename(columns={'date':'month'}, inplace=True)

In [118]:
df_result = pd.merge(df_raif, df_transponse, on='month', how='left')
df_result.drop(columns='month').to_csv('additional_metrics.csv', index=False)

In [123]:
df_test_raif = pd.read_csv('/Users/a19028558/Desktop/Ralf_Hack/test.csv')
dates_test_raif = set(df_raif['date'])
mapping = {}
for date in list(dates_test_raif):
    if date.split('-')[1] in date_collector:
        mapping[date] = date_collector[date.split('-')[1]]
    else:
        print('f')

In [125]:
df_test_raif['month'] = df_raif['date'].apply(lambda x: mapping[x])

In [127]:
df_test_raif

,city,floor,id,osm_amenity_points_in_0.001,osm_amenity_points_in_0.005,osm_amenity_points_in_0.0075,osm_amenity_points_in_0.01,osm_building_points_in_0.001,osm_building_points_in_0.005,osm_building_points_in_0.0075,...,reform_mean_year_building_500,region,lat,lng,total_square,street,date,realty_type,price_type,month
0,Курск,1.0,COL_289284,7,55,85,117,0,0,0,...,1966.740260,Курская область,51.709255,36.147908,156.148996,S6983,2020-09-06,100,1,январь
1,Сургут,1.0,COL_289305,8,70,112,140,0,0,0,...,1989.068182,Ханты-Мансийский АО,61.233240,73.462509,190.737943,S29120,2020-09-06,110,1,январь
2,Тюмень,-1.0,COL_289318,3,28,67,122,0,0,0,...,1991.458333,Тюменская область,57.143110,65.554573,457.118051,S23731,2020-09-06,10,1,январь
3,Иркутск,1.0,COL_289354,5,76,139,231,0,0,0,...,1941.657895,Иркутская область,52.281380,104.282975,66.503622,S14207,2020-09-06,100,1,январь
4,Курск,NaN,COL_289399,8,105,189,279,0,0,2,...,1946.689655,Курская область,51.729706,36.194019,23.864915,S20658,2020-09-06,10,1,январь
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2969,Красноярск,4.0,COL_455089,0,3,6,16,0,0,0,...,1982.250000,Красноярский край,55.978180,92.891457,2149.546362,S2650,2020-12-27,100,1,январь
2970,Томск,1.0,COL_455212,2,33,111,222,0,0,1,...,1973.460000,Томская область,56.459183,84.979872,359.371061,S11114,2020-12-27,10,1,январь
2971,Калуга,-1.0,COL_455261,2,25,54,99,0,0,0,...,1966.904762,Калужская область,54.523247,36.295168,87.820453,S34005,2020-12-27,100,1,январь
2972,Нижний Новгород,NaN,COL_455381,13,70,114,158,0,0,0,...,1946.529412,Нижегородская область,56.328236,43.990039,208.625735,S21753,2020-12-27,10,1,январь
2973,Нижний Новгород,NaN,COL_455397,1,52,111,146,0,0,0,...,1963.940000,Нижегородская область,56.343952,43.869360,232.109058,S28997,2020-12-27,100,1,январь